### ISSUE TITLE
Design: Japanese fonts aren't applied

### ISSUE THREAD

**Issue by kazuemon** [oruyanke/okayu-button#3]
## The Problem

When I change the language setting to Japanese, the Chinese font is used and the Japanese font is not applied.
当我将语言设置改为日语时，使用的是中文字体，而没有应用日语字体。

## Screenshot

![image](https://user-images.githubusercontent.com/12812934/88632747-fc2fb400-d0ee-11ea-9f92-281239715457.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/12812934/88633670-46fdfb80-d0f0-11ea-9535-59e8eb42f1d4.png)

**Comment by lonelyion** [comment]
The body font family are as follows:
`$body-font-family:  "Helvetica Neue",Helvetica,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","微软雅黑","-apple-system",BlinkMacSystemFont,"Yu Gothic Medium","游ゴシック Medium",YuGothic,"游ゴシック体","Noto Sans Japanese","ヒラギノ角ゴ Pro W3","メイリオ","Hiragino Kaku Gothic ProN","MS PGothic",Osaka,Arial,sans-serif;`

and if you don't install any Chinese fonts it will fallback to later Japanese fonts. And as far as I know, most of the Chinese fonts contains Japanese characters and they display well. So I think it's enough to just maintain this font-family list.

I wrote these fonts based on this post (in Chinese):
https://10.1pxeye.com/japanese-website-font-family-setting/

**Comment by kazuemon** [comment]
Thank you for your confirmation.
We can read the Japanese font included in the Chinese font, but it is not natural.
they are not suitable for Japanese users.

As an example, it shows naturally on this site.
https://player.banground.fun/
→ `Roboto,-apple-system,Helvetica Neue,Helvetica,Arial,sans-serif`

**Comment by lonelyion** [comment]
> We can read the Japanese font included in the Chinese font, but it is not natural.
> they are not suitable for Japanese users.

Ah I don't know that before. I just started learning Japanese and can't tell their difference lol.

**Comment by kazuemon** [comment]
Apparently the problem only occurs on Windows.

I'll see what I can do about it.

**Comment by lonelyion** [comment]
How about binding html class in default layout with computed property?

https://cn.vuejs.org/v2/guide/class-and-style.html

**Comment by lonelyion** [comment]
I've made a PR in main stream(fubuki-button) and you can preview at https://dev.fubuki.moe to see if there's more perfect solution

**Comment by kazuemon** [comment]
Sorry for the delay in replying.
The site you sent me is displaying correctly and is fine.

**Comment by lonelyion** [comment]
OK, I'll merge it into the repositories.
