### ISSUE TITLE
Bug: Live Stream Schedule won't be showed

### ISSUE THREAD

**Issue by kazuemon** [oruyanke/okayu-button#5]
# The Problem

There is no response from the API server to retrieve live schedule
没有来自API服务器的响应来检索实时时间表

# ScreenShot

![image](https://user-images.githubusercontent.com/12812934/88641045-a3194d80-d0f9-11ea-9c28-9bf8987bb8c2.png)

**Comment by lonelyion** [comment]
This is probably a change of HoloTools API endpoint. I'm asking the API maintainer and maybe we'll deploy our own API server to ensure the endpoint stable (Their endpoint is changing frequently lol).

**Comment by lonelyion** [comment]
Temporarily fixed by replacing url and some fields with the new endpoint.
