### ISSUE TITLE
关于合并仓库的提议

### ISSUE THREAD

**Issue by Cyame** [oruyanke/okayu-button#7]
首先感谢开发与维护，想就合并项目一事进行一下讨论

事因是由于我今天突然查了一下`okayu-button`的项目，原本想进入自己的。结果发现了这个同名项目。
于是重新挂了一次项目，目前在[仓库](https://github.com/Cyame/okayu-button)
（以及发现因为我这边是Fork了夸按钮所以默认搜不到x草）
所以想问问有没有合作的意向（不介意的话可以一起整合 至于用哪边的URL或者仓库也可以商量）

目前我的项目挂在了GitHub Pages和Gitee Pages上（暂时）因为奇声占比太大+开发工作我这边基本完成了但是音声收集人手不太够因此一直没能落地。
Gitee上也有[同名仓库](https://gitee.com/cyame/okayu-button) 分支是同时在两边推的。

目前我这边的情况大概是这样，想先通个气看看有没有意向。因为几乎是同期开始（我这边晚了一些）而且我这边确实没注意自己仓库搜不到的问题...因此可能做了不少重复工作

关于细节的讨论可以慢慢商量，再次感谢开发，以上。

**Comment by lonelyion** [comment]
啊这

加开源社区的群782052733讨论吧，我们目前是狐协和猫协合作的（）

**Comment by Cyame** [comment]
交 易 完 成
（音频整理中 预计本周末merge）
> 先Close~
